services:
  front:
    build:
      context: ./frontend-rss25
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-rss25:/app
      - /app/node_modules
    depends_on:
      - proxy
    command: npm run dev -- --host

  proxy:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: node server.js
